import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";

const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");
const index = await read("index.html");
const ui = await read("assets/saas-extension.js");
const core = await read("assets/saas-core.js");
const theme = await read("assets/saas-theme.css");

assert.match(index, /GP Mirari - MVP Local/);
assert.match(index, /function bindCriticalShellEvents\(\)/);
assert.match(index, /function renderModuleFailure\(error\)/);
assert.match(index, /data-module-recovery/);
assert.match(index, /const taskLabel = crmLeadIsClosed\(lead\)/, "Cartoes encerrados devem priorizar o resultado e a data no lugar da proxima tarefa.");
assert.match(index, /crmStage\(lead\.stageId\)\?\.name/);
assert.ok(
  index.indexOf("bindCriticalShellEvents();", index.indexOf("saveState();")) < index.indexOf("renderMetrics();", index.indexOf("saveState();")),
  "Navegacao e logout precisam ser vinculados antes da renderizacao do modulo ativo."
);
assert.match(index, /saas-core\.js/);
assert.match(index, /saas-extension\.js/);
assert.match(index, /saas-extension\.js\?v=20260820-pricing-safe-defaults/);
assert.match(index, /saas-theme\.css\?v=20260819-secure-report-share/);
assert.match(index, /saas-core\.js\?v=20260820-pricing-safe-defaults/);
assert.match(index, /reports-v4\.js\?v=20260819-secure-report-share/);
assert.match(index, /demoProjectCleanupVersion/, "A limpeza controlada dos projetos demonstrativos deve ser versionada.");
assert.match(index, /defaultState\.projects = \[\]/, "Novas instalacoes nao devem recriar projetos demonstrativos.");
assert.match(index, /Mural de tarefas/, "Projetos devem exibir o mural simplificado de tarefas.");
assert.match(index, /id="add-task-form" hidden/, "O cadastro de tarefa deve iniciar recolhido.");
assert.match(index, /function projectStageTasks\(/, "Tarefas devem usar ordenacao por andamento e prazo.");
assert.match(index, /name: "Thiago", username: "ADM"/, "O perfil principal deve manter o login ADM e exibir o nome do responsavel.");
assert.match(index, /user\.primary \? '<span class="pill">Principal<\/span>'/, "O usuario principal deve ser identificado na administracao.");
assert.match(index, /user\.primary \? user\.username : prompt/, "O login do usuario principal nao deve ser alterado pela edicao de perfil.");
assert.match(index, /task\.automatic && task\.required && !task\.completed/, "Somente regras administrativas obrigatorias podem bloquear o avanco.");
assert.match(index, /required: false,\s+automatic: false/, "Tarefas manuais nao podem bloquear o projeto.");
assert.match(index, /task\.workStatus = "Em andamento"/, "O mural deve suportar tarefas em andamento.");
assert.match(index, /data-task-check/, "Tarefas devem aceitar checklist em lista.");
assert.doesNotMatch(index, /id="task-required"/, "Obrigatoriedade nao deve ser configuravel no mural.");
assert.doesNotMatch(index, /Checklist opcional/, "A interface nao deve exibir o rotulo opcional.");
assert.match(index, /cloudStateUpdatedAt/, "O estado compartilhado deve rastrear sua revisao remota.");
assert.match(index, /state_conflict/, "Atualizacoes concorrentes devem ser bloqueadas.");
assert.match(index, /\.eq\("updated_at", cloudStateUpdatedAt\)/, "O salvamento deve usar controle otimista de concorrencia.");
assert.match(index, /cloudWriteQueue/, "Gravacoes do mesmo navegador devem ser serializadas.");
assert.match(index, /function queueStateWrite\(\)/, "A fila de sincronizacao precisa proteger contra falsos conflitos locais.");
assert.match(index, /proposalDraftSnapshots/, "Rascunhos recuperaveis devem ser mantidos no estado.");
assert.match(ui, /recordProposalDraftSnapshot/, "Cada rascunho de proposta deve criar uma copia recuperavel.");
assert.match(ui, /proposal-draft-history/, "A proposta deve permitir abrir o historico de rascunhos.");
assert.match(ui, /draft_restored/, "A restauracao de rascunho deve ficar registrada no historico.");
assert.match(index, /crm-optional-fields/);
assert.match(index, /Data do primeiro contato/);
assert.match(index, /Proxima tarefa/);
assert.match(index, /Responsavel pela tarefa/);
assert.match(index, /crmDashboardStats/);
assert.match(index, /crmTaskState/);
assert.match(index, /renderCommercialTasks/);
assert.match(index, /openCommercialTaskModal/);
assert.match(index, /crmRequiredPendingTasks/);
assert.match(index, /crmCanLeaveCurrentStage/);
assert.match(index, /Conclua as tarefas obrigatorias antes de avancar/);
assert.match(index, /data-edit-commercial-task/);
assert.match(index, /data-remove-commercial-task/);
assert.match(index, /renderAfterCommercialTaskChange/);
assert.match(index, /persistCommercialTaskMutation/);
assert.match(index, /legacyNextActionFor === lead\.id/);
assert.match(index, /crmLeadIsClosed/);
assert.match(index, /Oportunidades fechadas ou perdidas/);
assert.match(index, /addTaskBottom[\s\S]*bindCommercialTaskEvents\(\)/, "As tarefas comerciais do detalhe do CRM precisam reutilizar os eventos de concluir, editar e excluir.");
assert.match(index, /data-save-crm-template/);
assert.match(index, /crm-task-template-row/);
assert.match(index, /Tarefas manuais nao bloqueiam/);
assert.match(index, /openCRMCardConfig/);
assert.match(index, /id="card-config-won"[^>]*>Negocio fechado</, "O menu do cartao deve permitir concluir o negocio como fechado.");
assert.match(index, /id="card-config-lost"[^>]*>Negocio perdido</, "O menu do cartao deve permitir concluir o negocio como perdido.");
assert.match(index, /#card-config-won[\s\S]*state\.crm\.selectedLeadId = lead\.id;[\s\S]*closeCRMAsWon\(\)/, "O fechamento pelo menu deve agir sobre o cartao escolhido.");
assert.match(index, /#card-config-lost[\s\S]*state\.crm\.selectedLeadId = lead\.id;[\s\S]*closeCRMAsLost\(\)/, "A perda pelo menu deve agir sobre o cartao escolhido.");
assert.match(index, /leadLost[\s\S]*Motivo da perda:[\s\S]*lostReasonCategory/, "O menu de um negocio perdido deve exibir o motivo da perda no lugar das observacoes iniciais.");
assert.match(index, /Negocios encerrados nao permitem novas tarefas comerciais/, "O cadastro de tarefas deve bloquear oportunidades ganhas ou perdidas.");
assert.match(index, /selectableLeads[\s\S]*!crmLeadIsClosed\(lead\)/, "A lista de novas tarefas deve conter somente oportunidades abertas.");
assert.match(index, /function crmNextTask\(lead\) \{\s+if \(crmLeadIsClosed\(lead\)\) return null;/, "Negocios encerrados nao podem continuar exibindo tarefas atrasadas no cartao.");
assert.match(index, /leadClosed \? '<span class="pill">Negocio encerrado<\/span>'/, "O detalhe de um negocio encerrado nao deve oferecer uma nova tarefa.");
assert.match(index, /function crmCompleteTasksForClosedLead/, "O encerramento do negocio deve concluir suas tarefas comerciais.");
assert.match(index, /crmCompleteTasksForClosedLead\(lead, at, "won"\)/, "Negocios ganhos devem concluir todas as tarefas pendentes.");
assert.match(index, /crmCompleteTasksForClosedLead\(lead, at, "lost"\)/, "Negocios perdidos devem concluir todas as tarefas pendentes.");
assert.match(index, /task\.completedByCRMClosure = true/, "A conclusao automatica deve ficar identificada para auditoria.");
assert.match(index, /crmLeadClosureLabel\(lead\)/, "O cartao encerrado deve mostrar o resultado e a data do encerramento.");
assert.match(ui, /crmCompleteTasksForClosedLead\(lead,at,"won"\)/, "O fechamento originado pela proposta tambem deve concluir as tarefas comerciais.");
assert.match(index, /Tarefas comerciais/);
assert.match(index, /Sem proxima tarefa/);
assert.match(index, /chatNotifications/);
assert.match(index, /toggle-crm-lead/);
assert.match(index, /data-toggle-crm-lead/);
assert.match(index, /crm-opportunity-card/);
assert.match(index, /Recolher/);
assert.match(index, /crm-inline-add-label/);
assert.match(index, /crmLabelManageRows/);
assert.match(index, /data-inline-save-crm-label/);
assert.match(index, /data-inline-remove-crm-label/);
assert.match(index, /saveCrmLabel/);
assert.match(index, /removeCrmLabel/);
assert.match(index, /crm-detail-specifier/);
assert.match(index, /crm-specifier/);
assert.match(index, /formatMoneyInputValue/);
assert.match(index, /crmLeadClient/);
assert.doesNotMatch(index, /ficam recolhidos para manter o funil limpo/);
assert.match(index, /crmTouchStageAutomation/);
assert.match(index, /crmLossReasons/);
assert.match(index, /Motivo da perda/);
assert.match(index, /if \(lost\) lost\.onclick = \(\) => closeCRMAsLost\(\);/, "O clique em negocio perdido nao pode enviar o evento do botao como motivo da perda.");
assert.match(index, /typeof reasonValue === "string" \? reasonValue\.trim\(\) : ""/, "O motivo da perda deve aceitar apenas o valor selecionado no formulario.");
assert.match(index, /if \(closeCRMAsLost\(reason, comment\)\) modal\.remove\(\);/, "O formulario de perda deve permanecer aberto quando a conclusao for cancelada ou rejeitada.");
assert.match(index, /Tempo medio fechamento/);
assert.match(index, /Valor ponderado/);
assert.match(index, /Ciclo total/);
assert.doesNotMatch(index, /SUPABASE_SERVICE_ROLE_KEY/);
assert.doesNotMatch(index, /password: "12345"/, "production source must not ship default passwords");
assert.match(index, /function isDemoMode\(\)/, "demo mode must be explicit");
assert.match(index, /function expectsCloudAuth\(\)/, "configured cloud auth must not fall back to local login");
assert.match(index, /Login local desativado/, "local login must be blocked outside demo mode");
assert.match(index, /localStorage\.removeItem\(storageKey\)/, "logout/session invalidation must clear cached workspace");
assert.match(ui, /sales-scenario/, "A negociacao deve permitir selecionar cenarios salvos.");
assert.match(ui, /data-new-scenario/, "A negociacao deve permitir criar um novo cenario.");
assert.match(ui, /data-entry-percent/, "A vista com entrada deve permitir editar o percentual de entrada.");
assert.match(ui, /data-split-percent/, "As parcelas devem suportar percentuais individuais.");
assert.match(ui, /Valor bruto:/, "O valor bruto deve acompanhar o valor final negociado.");
assert.match(core, /CommercialRepository/);
assert.match(core, /calculateProposal/);
assert.match(core, /calculatePaymentOptions/);
assert.match(core, /calculatePriceFormation/);
assert.match(core, /13\.41/);
assert.match(core, /defaultStoreRates/);
assert.match(core, /baseUnitCents/);
assert.match(ui, /Clientes/);
assert.match(ui, /Base de especificadores/);
assert.match(ui, /data-client-delete/);
assert.match(ui, /deleteClient/);
assert.match(ui, /Propostas/);
assert.match(ui, /Produto ou ambiente/);
assert.match(ui, /Markup \(%\)/);
assert.match(ui, /RT global \(%\)/);
assert.match(ui, /Resumo em tempo real/);
assert.match(ui, /Gerar PDF/);
assert.match(ui, /installmentPayments:condition===\x27cash_entry\x27/, "O PDF da negociacao deve carregar os valores das parcelas simuladas.");
assert.match(ui, /configuredPayment=conditionDefinition\(\)/, "O PDF deve usar a definicao da condicao sem reaplicar a taxa financeira.");
assert.match(ui, /sales-card-installments/, "A tela de negociacao deve permitir escolher as parcelas do cartao.");
assert.match(ui, /conditionMultiplierFor/, "A negociacao deve calcular ambientes sobre a condicao de pagamento selecionada.");
assert.match(ui, /simulation\.cardInstallments\?\.card/, "O PDF deve respeitar o parcelamento de cartao escolhido na simulacao.");
assert.match(ui, /saas-summary-compact/, "O resumo da proposta deve apresentar informacoes principais de forma compacta.");
assert.match(theme, /saas-proposal-summary \.saas-final-only \{[^}]*font-size: 15px !important/, "O preco final do resumo deve usar tipografia compacta.");
assert.match(ui, /function openSalesWorkspace\(proposal\)/);
assert.match(ui, /Tela de vendas/);
assert.match(ui, /data-item/);
assert.match(ui, /Desconto global efetivo/);
assert.doesNotMatch(ui, /Salvar negociacao/, "A negociacao deve usar salvamento automatico.");
assert.match(ui, /Nova simulacao/, "Deve iniciar uma simulacao limpa.");
assert.match(ui, /O valor final nao pode ser maior que o valor bruto/, "O valor final deve respeitar o valor bruto.");
assert.match(ui, /Aprovar negociacao/, "O botao de formalizacao deve ter texto visivel.");
assert.match(ui, /Math\.min\(3,Number\(payment\.installments\)/, "A negociacao deve permitir ate tres parcelas.");
assert.match(ui, /syncPaymentInputs/, "Valores e percentuais devem sincronizar durante a digitacao.");
assert.match(ui, /data-item-lock/, "Valores manuais devem oferecer bloqueio por ambiente.");
assert.match(ui, /locked:false,manualTotalCents:null,discountPercent:0/, "Desbloquear um ambiente deve remover sua base manual para voltar ao desconto global.");
assert.match(ui, /overallDiscountPercent/, "O topo deve exibir o desconto efetivo da proposta.");
assert.match(ui, /rebalanceSplit/, "A parcela editada deve redistribuir o percentual restante.");
assert.doesNotMatch(ui, /Entrada e parcelas totalizam 100%/, "O resumo redundante de 100% deve ser removido.");
assert.match(ui, /\[data-entry-value\]/, "Campos monetarios da entrada devem receber mascara em reais.");
assert.match(ui, /Custos, markup e proposta-base permanecem protegidos/);
assert.match(ui, /saas-line-drag-handle/);
assert.match(ui, /refreshLineOrderControls/);
assert.doesNotMatch(ui, /data-line-move=/);
assert.match(ui, /onpointerdown/);
assert.match(ui, /modal\.scrollTop/);
assert.match(ui, /saas-line-drop-before/);
assert.match(ui, /saas-line-drop-after/);
assert.match(ui, /Previsao de entrega/);
assert.match(ui, /Condi&ccedil;&otilde;es de pagamento/);
assert.match(ui, /payment-entry-value/);
assert.match(ui, /paymentDiscount/);
assert.match(ui, /pricedItemsForCondition/);
assert.match(ui, /Juros sobre o saldo/);
assert.match(ui, /Parcelas apos entrada/);
assert.match(ui, /admin-card-fixed-rate/);
assert.match(ui, /data-store-rate/);
assert.match(ui, /Liberar markup e desconto/);
assert.match(ui, /Senha do ADM/);
assert.match(ui, /Usuario ADM/);
assert.match(ui, /verifyAdminCredentials/);
assert.match(ui, /persistSession:false/);
assert.match(ui, /autoRefreshToken:false/);
assert.doesNotMatch(ui, /editable&&!admin\(\)\?'<button class="saas-button" id="unlock-commercial-edit"/);
assert.match(ui, /\(admin\(\)\|\|commercialOverride\)\?requestedDiscount/);
assert.match(ui, /line\(item=\{\},commercialEditAllowed=admin\(\),editable=true\)/);
assert.match(ui, /const markupValue=hasComposition\?subItemsAverageMarkupPercent/, "A composicao deve expor o markup medio ponderado.");
assert.match(ui, /currentProposal\?\.status==="internal_review"&&admin\(\)/);
assert.match(ui, /Somente ADM pode aprovar propostas/);
assert.match(ui, /enforceRoleVisibility/);
assert.match(ui, /function ensureRepository/);
assert.match(ui, /repo\.shared!==state/);
assert.match(ui, /\(state\.clients\|\|\[\]\)\.filter/);
assert.match(ui, /\(state\.proposals\|\|\[\]\)\.filter/);
assert.match(ui, /Propostas vinculadas/);
assert.match(ui, /data-open-crm-proposal/);
assert.doesNotMatch(ui, /desconto em relacao a maior condicao/);
assert.match(core, /Cartao de credito/);
assert.match(core, /Parcelado loja/);
assert.match(core, /A vista com entrada/);
assert.match(ui, /Regras comerciais/);
assert.match(ui, /Somente ADM pode utilizar markup abaixo do padrao/);
assert.match(ui, /Parcelas individuais/);
assert.match(ui, /Configurar subitens/);
assert.match(ui, /Custo de producao/);
assert.match(ui, /Valor de venda da composicao/);
assert.match(ui, /composition-markup/);
assert.match(ui, /subItemsAverageMarkupPercent/, "O markup externo deve refletir a media ponderada dos subitens.");
assert.match(ui, /markup\.value=String\(subItemsAverageMarkupPercent/, "A alteracao interna deve atualizar o markup visual externo.");
assert.match(ui, /Formacao de preco/);
assert.match(ui, /Pontuacao da venda/);
assert.match(ui, /Venda liquida - RT/);
assert.match(ui, /RT liquida da formacao/);
assert.doesNotMatch(ui, /RT adicionada ao preco/, "O resumo deve exibir apenas o preco final.");
assert.match(ui, /Base da RT liquida/);
assert.match(ui, /Editar impostos e comissoes/);
assert.match(ui, /Padroes de frete e montagem/);
assert.match(ui, /Venda e custo por ambiente/);
assert.match(ui, /Taxas financeiras/);
assert.match(ui, /Condicao de pagamento analisada/, "A formacao de preco deve permitir escolher a condicao comercial analisada.");
assert.match(ui, /source\.type!=="cash"&&source\.type!=="pix"/, "A vista deve ser incluida uma unica vez e as demais condicoes habilitadas devem ser preservadas.");
assert.match(ui, /saleCents:calculated\.totalCents/, "Cada condicao deve levar seu preco de venda calculado para a formacao.");
assert.match(ui, /financialFeeCents/, "A formacao deve separar preco de venda e custo financeiro.");
assert.match(core, /freightPercent: 10/, "Frete deve iniciar em 10%.");
assert.match(ui, /parsed>0\?parsed:fallback/, "Configuracoes antigas zeradas devem voltar ao padrao seguro.");
assert.match(ui, /pricingDefaultsVersion:1/, "Ajustes manuais posteriores devem ser identificados e preservados.");
assert.match(ui, /Retornar a negociacao/);
assert.match(ui, /Iniciar negociacao/);
assert.match(ui, /Propostas vencidas/);
assert.match(ui, /proposal-client-filter/);
assert.match(ui, /proposal-opportunity-filter/);
assert.match(ui, /Follow-up de validade/);
assert.match(ui, /view-expired-proposals/);
assert.match(ui, /clear-proposal-filters-shortcut/);
assert.match(ui, /renderProposalGlobalMetrics/);
assert.match(ui, /Envolvidos e comissoes/);
assert.match(ui, /cash-entry-balance/);
assert.match(ui, /Distribua integralmente o saldo/);
assert.match(ui, /editable&&admin\(\)\?'<button class="saas-button" id="unlock-commercial-edit"/);
assert.match(core, /recordLeadHistory/);
assert.match(core, /netSaleBeforeRtCents/);
assert.match(core, /saleScore/);
assert.match(core, /addPercentFromNet/);
assert.match(ui, /proposalPricingOptions/);
assert.match(ui, /Produtos e ambientes/);
assert.match(ui, /Nao foi possivel concluir o negocio/);

const coreContext = { Intl, localStorage: { getItem: () => null }, globalThis: {} };
vm.runInNewContext(core, coreContext);
assert.equal(typeof coreContext.globalThis.GPMirariCommercial?.CommercialRepository, "function");
const conditionNegotiation = coreContext.globalThis.GPMirariCommercial.calculateSalesNegotiation({ items: [{ id: "condition-item", name: "Ambiente", baseUnitCents: 100000, quantity: 1, markupPercent: 0 }], globalRtEnabled: false }, { selectedItemIds: ["condition-item"], conditionMultiplier: 1.1 });
assert.equal(conditionNegotiation.grossTotalCents, 110000, "O valor bruto por ambiente deve acompanhar o multiplicador da condicao de pagamento.");
const repositoryState = { users: [{ id: "u1", name: "Administrador", permission: "ADM", active: true }], clients: [], proposals: [], projects: [], crm: { leads: [{ id: "lead1", client: "Cliente CRM", history: [] }] } };
const repository = new coreContext.globalThis.GPMirariCommercial.CommercialRepository(repositoryState);
const proposal = repository.saveProposal({ crmOpportunityRef: "lead1", clientId: repositoryState.crm.leads[0].clientId, validUntil: "2026-08-01", items: [{ name: "Ambiente", baseUnitCents: 100000, quantity: 1, markupPercent: 0, hasRt: false, rtPercent: 0 }] }, "Administrador");
assert.match(repositoryState.crm.leads[0].history[0].text, /criada e vinculada/);
repository.transition(proposal.id, "negotiation", "Administrador");
assert.equal(proposal.status, "negotiation");
repository.transition(proposal.id, "internal_review", "Administrador");
assert.match(repositoryState.crm.leads[0].history.at(-1).text, /Em aprovacao/);
repository.transition(proposal.id, "approved", "Administrador");
const returned = repository.transition(proposal.id, "negotiation", "Administrador", "Retornada a negociacao: ajuste interno");
assert.equal(returned.status, "negotiation");
repository.transition(proposal.id, "internal_review", "Administrador");
repository.transition(proposal.id, "approved", "Administrador");
repository.transition(proposal.id, "sent", "Administrador");
repository.transition(proposal.id, "accepted", "Administrador");
const acceptedReturn = repository.transition(proposal.id, "negotiation", "Administrador", "Retornada a negociacao apos aceite");
assert.equal(acceptedReturn.status, "negotiation");
console.log("validate-release.mjs: ok");
