import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";

const root = new URL("../", import.meta.url);
const read = (path) => readFile(new URL(path, root), "utf8");
const index = await read("index.html");
const ui = await read("assets/saas-extension.js");
const core = await read("assets/saas-core.js");

assert.match(index, /GP Mirari - MVP Local/);
assert.match(index, /function bindCriticalShellEvents\(\)/);
assert.match(index, /function renderModuleFailure\(error\)/);
assert.match(index, /data-module-recovery/);
assert.match(index, /const taskLabel = !nextTask/);
assert.match(index, /crmStage\(lead\.stageId\)\?\.name/);
assert.ok(
  index.indexOf("bindCriticalShellEvents();", index.indexOf("saveState();")) < index.indexOf("renderMetrics();", index.indexOf("saveState();")),
  "Navegacao e logout precisam ser vinculados antes da renderizacao do modulo ativo."
);
assert.match(index, /saas-core\.js/);
assert.match(index, /saas-extension\.js/);
assert.match(index, /saas-extension\.js\?v=20260811-sales-workspace/);
assert.match(index, /saas-theme\.css\?v=20260811-sales-workspace/);
assert.match(index, /saas-core\.js\?v=20260805-proposal-dashboard-fix/);
assert.match(index, /crm-optional-fields/);
assert.match(index, /Data do primeiro contato/);
assert.match(index, /Proxima tarefa/);
assert.match(index, /Responsavel pela tarefa/);
assert.match(index, /crmDashboardStats/);
assert.match(index, /crmTaskState/);
assert.match(index, /renderCommercialTasks/);
assert.match(index, /openCommercialTaskModal/);
assert.match(index, /crmRequiredPendingTasks/);
assert.match(index, /crmCanLeaveCurrentStage/);
assert.match(index, /Conclua as tarefas obrigatorias antes de avancar/);
assert.match(index, /data-edit-commercial-task/);
assert.match(index, /data-remove-commercial-task/);
assert.match(index, /renderAfterCommercialTaskChange/);
assert.match(index, /persistCommercialTaskMutation/);
assert.match(index, /legacyNextActionFor === lead\.id/);
assert.match(index, /crmLeadIsClosed/);
assert.match(index, /Oportunidades fechadas ou perdidas/);
assert.match(index, /addTaskBottom[\s\S]*bindCommercialTaskEvents\(\)/, "As tarefas comerciais do detalhe do CRM precisam reutilizar os eventos de concluir, editar e excluir.");
assert.match(index, /data-save-crm-template/);
assert.match(index, /crm-task-template-row/);
assert.match(index, /Tarefas manuais nao bloqueiam/);
assert.match(index, /openCRMCardConfig/);
assert.match(index, /Tarefas comerciais/);
assert.match(index, /Sem proxima tarefa/);
assert.match(index, /chatNotifications/);
assert.match(index, /toggle-crm-lead/);
assert.match(index, /data-toggle-crm-lead/);
assert.match(index, /crm-opportunity-card/);
assert.match(index, /Recolher/);
assert.match(index, /crm-inline-add-label/);
assert.match(index, /crmLabelManageRows/);
assert.match(index, /data-inline-save-crm-label/);
assert.match(index, /data-inline-remove-crm-label/);
assert.match(index, /saveCrmLabel/);
assert.match(index, /removeCrmLabel/);
assert.match(index, /crm-detail-specifier/);
assert.match(index, /crm-specifier/);
assert.match(index, /formatMoneyInputValue/);
assert.match(index, /crmLeadClient/);
assert.doesNotMatch(index, /ficam recolhidos para manter o funil limpo/);
assert.match(index, /crmTouchStageAutomation/);
assert.match(index, /crmLossReasons/);
assert.match(index, /Motivo da perda/);
assert.match(index, /Tempo medio fechamento/);
assert.match(index, /Valor ponderado/);
assert.match(index, /Ciclo total/);
assert.doesNotMatch(index, /SUPABASE_SERVICE_ROLE_KEY/);
assert.doesNotMatch(index, /password: "12345"/, "production source must not ship default passwords");
assert.match(index, /function isDemoMode\(\)/, "demo mode must be explicit");
assert.match(index, /function expectsCloudAuth\(\)/, "configured cloud auth must not fall back to local login");
assert.match(index, /Login local desativado/, "local login must be blocked outside demo mode");
assert.match(index, /localStorage\.removeItem\(storageKey\)/, "logout/session invalidation must clear cached workspace");
assert.match(core, /CommercialRepository/);
assert.match(core, /calculateProposal/);
assert.match(core, /calculatePaymentOptions/);
assert.match(core, /calculatePriceFormation/);
assert.match(core, /13\.41/);
assert.match(core, /defaultStoreRates/);
assert.match(core, /baseUnitCents/);
assert.match(ui, /Clientes/);
assert.match(ui, /Base de especificadores/);
assert.match(ui, /data-client-delete/);
assert.match(ui, /deleteClient/);
assert.match(ui, /Propostas/);
assert.match(ui, /Produto ou ambiente/);
assert.match(ui, /Markup \(%\)/);
assert.match(ui, /RT global \(%\)/);
assert.match(ui, /Resumo em tempo real/);
assert.match(ui, /Gerar PDF/);
assert.match(ui, /function openSalesWorkspace\(proposal\)/);
assert.match(ui, /Tela de vendas/);
assert.match(ui, /data-sales-item/);
assert.match(ui, /Desconto da negociacao/);
assert.match(ui, /Visualizar apresentacao/);
assert.match(ui, /Custos, markup e margem permanecem internos/);
assert.match(ui, /saas-line-drag-handle/);
assert.match(ui, /refreshLineOrderControls/);
assert.doesNotMatch(ui, /data-line-move=/);
assert.match(ui, /onpointerdown/);
assert.match(ui, /modal\.scrollTop/);
assert.match(ui, /saas-line-drop-before/);
assert.match(ui, /saas-line-drop-after/);
assert.match(ui, /Previsao de entrega/);
assert.match(ui, /Condi&ccedil;&otilde;es de pagamento/);
assert.match(ui, /payment-entry-value/);
assert.match(ui, /paymentDiscount/);
assert.match(ui, /pricedItemsForCondition/);
assert.match(ui, /Juros sobre o saldo/);
assert.match(ui, /Parcelas apos entrada/);
assert.match(ui, /admin-card-fixed-rate/);
assert.match(ui, /data-store-rate/);
assert.match(ui, /Liberar markup e desconto/);
assert.match(ui, /Senha do ADM/);
assert.match(ui, /Usuario ADM/);
assert.match(ui, /verifyAdminCredentials/);
assert.match(ui, /persistSession:false/);
assert.match(ui, /autoRefreshToken:false/);
assert.doesNotMatch(ui, /editable&&!admin\(\)\?'<button class="saas-button" id="unlock-commercial-edit"/);
assert.match(ui, /\(admin\(\)\|\|commercialOverride\)\?requestedDiscount/);
assert.match(ui, /line\(item=\{\},commercialEditAllowed=admin\(\),editable=true\)/);
assert.match(ui, /const markupValue=savedMarkup/);
assert.match(ui, /currentProposal\?\.status==="internal_review"&&admin\(\)/);
assert.match(ui, /Somente ADM pode aprovar propostas/);
assert.match(ui, /enforceRoleVisibility/);
assert.match(ui, /function ensureRepository/);
assert.match(ui, /repo\.shared!==state/);
assert.match(ui, /\(state\.clients\|\|\[\]\)\.filter/);
assert.match(ui, /\(state\.proposals\|\|\[\]\)\.filter/);
assert.match(ui, /Propostas vinculadas/);
assert.match(ui, /data-open-crm-proposal/);
assert.doesNotMatch(ui, /desconto em relacao a maior condicao/);
assert.match(core, /Cartao de credito/);
assert.match(core, /Parcelado loja/);
assert.match(core, /A vista com entrada/);
assert.match(ui, /Regras comerciais/);
assert.match(ui, /Somente ADM pode utilizar markup abaixo do padrao/);
assert.match(ui, /Parcelas individuais/);
assert.match(ui, /Configurar subitens/);
assert.match(ui, /Custo de producao/);
assert.match(ui, /Valor de venda da composicao/);
assert.match(ui, /composition-markup/);
assert.match(ui, /Formacao de preco/);
assert.match(ui, /Pontuacao da venda/);
assert.match(ui, /Venda liquida - RT/);
assert.match(ui, /RT liquida da formacao/);
assert.match(ui, /RT adicionada ao preco/);
assert.match(ui, /Base da RT liquida/);
assert.match(ui, /Editar impostos e comissoes/);
assert.match(ui, /Padroes de frete e montagem/);
assert.match(ui, /Venda e custo por ambiente/);
assert.match(ui, /Taxas financeiras/);
assert.match(ui, /Retornar a negociacao/);
assert.match(ui, /Iniciar negociacao/);
assert.match(ui, /Propostas vencidas/);
assert.match(ui, /proposal-client-filter/);
assert.match(ui, /proposal-opportunity-filter/);
assert.match(ui, /Follow-up de validade/);
assert.match(ui, /view-expired-proposals/);
assert.match(ui, /clear-proposal-filters-shortcut/);
assert.match(ui, /renderProposalGlobalMetrics/);
assert.match(ui, /Envolvidos e comissoes/);
assert.match(ui, /cash-entry-balance/);
assert.match(ui, /Distribua integralmente o saldo/);
assert.match(ui, /editable&&admin\(\)\?'<button class="saas-button" id="unlock-commercial-edit"/);
assert.match(core, /recordLeadHistory/);
assert.match(core, /netSaleBeforeRtCents/);
assert.match(core, /saleScore/);
assert.match(core, /addPercentFromNet/);
assert.match(ui, /proposalPricingOptions/);
assert.match(ui, /Produtos e ambientes/);
assert.match(ui, /Nao foi possivel concluir o negocio/);

const coreContext = { Intl, localStorage: { getItem: () => null }, globalThis: {} };
vm.runInNewContext(core, coreContext);
assert.equal(typeof coreContext.globalThis.GPMirariCommercial?.CommercialRepository, "function");
const repositoryState = { users: [{ id: "u1", name: "Administrador", permission: "ADM", active: true }], clients: [], proposals: [], projects: [], crm: { leads: [{ id: "lead1", client: "Cliente CRM", history: [] }] } };
const repository = new coreContext.globalThis.GPMirariCommercial.CommercialRepository(repositoryState);
const proposal = repository.saveProposal({ crmOpportunityRef: "lead1", clientId: repositoryState.crm.leads[0].clientId, validUntil: "2026-08-01", items: [{ name: "Ambiente", baseUnitCents: 100000, quantity: 1, markupPercent: 0, hasRt: false, rtPercent: 0 }] }, "Administrador");
assert.match(repositoryState.crm.leads[0].history[0].text, /criada e vinculada/);
repository.transition(proposal.id, "negotiation", "Administrador");
assert.equal(proposal.status, "negotiation");
repository.transition(proposal.id, "internal_review", "Administrador");
assert.match(repositoryState.crm.leads[0].history.at(-1).text, /Em aprovacao/);
repository.transition(proposal.id, "approved", "Administrador");
const returned = repository.transition(proposal.id, "negotiation", "Administrador", "Retornada a negociacao: ajuste interno");
assert.equal(returned.status, "negotiation");
repository.transition(proposal.id, "internal_review", "Administrador");
repository.transition(proposal.id, "approved", "Administrador");
repository.transition(proposal.id, "sent", "Administrador");
repository.transition(proposal.id, "accepted", "Administrador");
const acceptedReturn = repository.transition(proposal.id, "negotiation", "Administrador", "Retornada a negociacao apos aceite");
assert.equal(acceptedReturn.status, "negotiation");
console.log("validate-release.mjs: ok");
